import type { DataModelSchemaResponse } from "../shared/contracts";

export const dataModelSchema: DataModelSchemaResponse = {
  version: "2026-05-14.phase6",
  migrationOrder: [
    "User",
    "TravellerProfile",
    "CompanionProfile",
    "Experience",
    "AvailabilityWindow",
    "Inquiry",
    "PaymentRecord",
    "StripeWebhookEvent",
    "SafetyReport",
    "AuditEvent",
  ],
  entities: [
    {
      name: "User",
      storageTarget: "D1",
      fields: [
        { name: "id", type: "text primary key", required: true, private: false, note: "Stable user identifier." },
        { name: "email", type: "text unique", required: true, private: true, note: "Account contact; never public profile copy." },
        { name: "role", type: "traveller | companion", required: true, private: false, note: "Customer-facing role only." },
        { name: "status", type: "active | restricted | suspended", required: true, private: false, note: "Session eligibility state." },
        { name: "createdAt", type: "datetime", required: true, private: false, note: "Audit timestamp." },
        { name: "updatedAt", type: "datetime", required: true, private: false, note: "Audit timestamp." },
      ],
      relationships: ["TravellerProfile.userId", "CompanionProfile.userId", "SafetyReport.reporterUserId"],
      states: ["pending_auth", "active", "restricted", "suspended"],
    },
    {
      name: "TravellerProfile",
      storageTarget: "D1",
      fields: [
        { name: "id", type: "text primary key", required: true, private: false, note: "Traveller profile id." },
        { name: "userId", type: "text foreign key User.id", required: true, private: true, note: "Owner relation." },
        { name: "cityInterest", type: "CitySlug", required: false, private: false, note: "Discovery preference." },
        { name: "experienceInterest", type: "ExperienceSlug", required: false, private: false, note: "Discovery preference." },
        { name: "privacySettings", type: "json", required: true, private: true, note: "Account privacy preferences." },
      ],
      relationships: ["Inquiry.travellerProfileId", "PaymentRecord.travellerProfileId"],
      states: ["active", "restricted"],
    },
    {
      name: "CompanionProfile",
      storageTarget: "D1",
      fields: [
        { name: "id", type: "text primary key", required: true, private: false, note: "Companion profile id." },
        { name: "userId", type: "text foreign key User.id", required: true, private: true, note: "Owner relation." },
        { name: "displayName", type: "text", required: true, private: false, note: "Public-safe after review." },
        { name: "legalName", type: "text", required: true, private: true, note: "Review-only identity field." },
        { name: "publicBio", type: "text", required: true, private: false, note: "Reviewed public copy." },
        { name: "privateReviewNote", type: "text", required: true, private: true, note: "Review-only context." },
        { name: "city", type: "CitySlug", required: true, private: false, note: "Visibility-controlled city." },
        { name: "experienceTags", type: "json ExperienceSlug[]", required: true, private: false, note: "Itinerary contexts." },
        { name: "visibilitySettings", type: "json", required: true, private: false, note: "Controls public exposure and inquiries." },
        { name: "reviewStatus", type: "CompanionReviewStatus", required: true, private: false, note: "Moderation status." },
      ],
      relationships: ["AvailabilityWindow.companionProfileId", "Inquiry.companionProfileId"],
      states: ["draft", "pending_verification", "changes_requested", "approved", "rejected", "hidden", "suspended"],
    },
    {
      name: "Experience",
      storageTarget: "KV",
      fields: [
        { name: "slug", type: "ExperienceSlug", required: true, private: false, note: "Stable lookup key." },
        { name: "city", type: "CitySlug", required: true, private: false, note: "City label." },
        { name: "title", type: "text", required: true, private: false, note: "Public label." },
        { name: "summary", type: "text", required: true, private: false, note: "Public-safe experience summary." },
        { name: "safetyNote", type: "text", required: true, private: false, note: "Safety framing." },
      ],
      relationships: ["CompanionProfile.experienceTags", "Inquiry.experience"],
      states: ["active", "hidden"],
    },
    {
      name: "AvailabilityWindow",
      storageTarget: "D1",
      fields: [
        { name: "id", type: "text primary key", required: true, private: false, note: "Availability id." },
        { name: "companionProfileId", type: "text foreign key CompanionProfile.id", required: true, private: true, note: "Owner relation." },
        { name: "city", type: "CitySlug", required: true, private: false, note: "Planning city." },
        { name: "label", type: "text", required: true, private: false, note: "Non-urgent window label." },
        { name: "status", type: "available | tentative | hidden", required: true, private: false, note: "Visibility-safe status." },
        { name: "note", type: "text", required: true, private: false, note: "Planning note." },
      ],
      relationships: ["CompanionProfile.availabilityWindows"],
      states: ["available", "tentative", "hidden"],
    },
    {
      name: "Inquiry",
      storageTarget: "D1",
      fields: [
        { name: "id", type: "text primary key", required: true, private: false, note: "Inquiry id." },
        { name: "travellerProfileId", type: "text foreign key TravellerProfile.id", required: true, private: true, note: "Traveller relation." },
        { name: "companionProfileId", type: "text foreign key CompanionProfile.id", required: true, private: true, note: "Companion relation." },
        { name: "city", type: "CitySlug", required: true, private: false, note: "Requested city." },
        { name: "experience", type: "ExperienceSlug", required: true, private: false, note: "Requested experience." },
        { name: "message", type: "text", required: true, private: true, note: "Private inquiry message." },
        { name: "status", type: "InquiryStatus", required: true, private: false, note: "Inquiry state." },
      ],
      relationships: ["PaymentRecord.inquiryId", "SafetyReport.targetId"],
      states: ["draft", "submitted", "under_review", "payment_review", "routed", "accepted", "declined", "cancelled"],
    },
    {
      name: "PaymentRecord",
      storageTarget: "D1",
      fields: [
        { name: "id", type: "text primary key", required: true, private: false, note: "Payment record id." },
        { name: "inquiryId", type: "text foreign key Inquiry.id", required: true, private: true, note: "Inquiry relation." },
        { name: "provider", type: "PaymentProviderSummary.id", required: true, private: false, note: "Stripe or approved alternative." },
        { name: "status", type: "disabled_for_compliance | checkout_created | succeeded | failed", required: true, private: false, note: "Compliance-aware state." },
        { name: "complianceState", type: "compliance_hold | provider_approved", required: true, private: false, note: "Live payment gate." },
        { name: "idempotencyKey", type: "text unique", required: true, private: true, note: "Duplicate protection." },
      ],
      relationships: ["StripeWebhookEvent.paymentRecordId"],
      states: ["disabled_for_compliance", "draft", "checkout_created", "requires_action", "processing", "succeeded", "failed", "cancelled", "refunded", "disputed"],
    },
    {
      name: "StripeWebhookEvent",
      storageTarget: "D1",
      fields: [
        { name: "id", type: "text primary key", required: true, private: false, note: "Webhook event record id." },
        { name: "stripeEventId", type: "text unique", required: true, private: false, note: "Stripe event id for idempotency." },
        { name: "signatureVerified", type: "boolean", required: true, private: false, note: "Must be true before state mutation." },
        { name: "processingStatus", type: "received | processed | duplicate | failed | ignored", required: true, private: false, note: "Webhook processing state." },
      ],
      relationships: ["PaymentRecord.id"],
      states: ["received", "processed", "duplicate", "failed", "ignored"],
    },
    {
      name: "SafetyReport",
      storageTarget: "D1",
      fields: [
        { name: "id", type: "text primary key", required: true, private: false, note: "Safety report id." },
        { name: "reporterUserId", type: "text foreign key User.id", required: false, private: true, note: "Optional reporter relation." },
        { name: "targetType", type: "profile | inquiry | payment | account | other", required: true, private: false, note: "Target category." },
        { name: "targetId", type: "text", required: false, private: true, note: "Target id if known." },
        { name: "reasonCategory", type: "privacy | unsafe_request | payment_pressure | profile_accuracy | other", required: true, private: false, note: "Moderation category." },
        { name: "summary", type: "text", required: true, private: true, note: "Private report details." },
        { name: "status", type: "submitted | triaged | investigating | resolved | escalated", required: true, private: false, note: "Moderation workflow state." },
      ],
      relationships: ["User.id"],
      states: ["submitted", "triaged", "investigating", "resolved", "escalated"],
    },
    {
      name: "AuditEvent",
      storageTarget: "D1",
      fields: [
        { name: "id", type: "text primary key", required: true, private: false, note: "Audit event id." },
        { name: "actorUserId", type: "text foreign key User.id", required: false, private: true, note: "Actor relation when available." },
        { name: "eventType", type: "text", required: true, private: false, note: "Action category." },
        { name: "target", type: "text", required: true, private: false, note: "Target entity." },
        { name: "requestId", type: "text", required: true, private: false, note: "Request ID propagation link." },
      ],
      relationships: ["User.id"],
      states: ["recorded"],
    },
  ],
};
