import type { ApiRouteDefinition, ApiRouteRegistryResponse } from "../shared/contracts";

export const apiRouteRegistry: ApiRouteDefinition[] = [
  {
    method: "GET",
    path: "/api/system/routes",
    audience: "system",
    handler: "system.routes",
    responseContract: "ApiRouteRegistryResponse",
    auth: "anonymous",
    stagedProvider: "route-registry",
    productionTarget: "worker",
    notes: "Machine-readable API route registry for implementation and contract smoke tests.",
  },
  {
    method: "GET",
    path: "/api/system/storage-boundaries",
    audience: "system",
    handler: "system.storageBoundaries",
    responseContract: "StorageBoundaryResponse",
    auth: "anonymous",
    stagedProvider: "storage-boundaries",
    productionTarget: "worker",
    notes: "Documents D1, R2, and KV ownership before production persistence is enabled.",
  },
  {
    method: "GET",
    path: "/api/system/data-model",
    audience: "system",
    handler: "system.dataModel",
    responseContract: "DataModelSchemaResponse",
    auth: "anonymous",
    stagedProvider: "data-model-schema",
    productionTarget: "worker",
    notes: "Exposes the implementation-ready data model schema draft.",
  },
  {
    method: "GET",
    path: "/api/public/home",
    audience: "public",
    handler: "public.home",
    responseContract: "PublicHomeResponse",
    auth: "anonymous",
    stagedProvider: "stagedDataProvider.getHome",
    productionTarget: "KV",
    notes: "Public brand, city, trust, and entry path payload.",
  },
  {
    method: "GET",
    path: "/api/public/experiences?city=&category=",
    audience: "public",
    handler: "public.experiences",
    responseContract: "ExperienceSummary[]",
    auth: "anonymous",
    stagedProvider: "stagedDataProvider.listExperiences",
    productionTarget: "D1",
    notes: "City and experience surfaces are API-backed, not embedded in UI components.",
  },
  {
    method: "POST",
    path: "/api/muse/chat",
    audience: "muse",
    handler: "muse.chat",
    requestContract: "MuseChatRequest",
    responseContract: "MuseChatResponse",
    auth: "anonymous",
    stagedProvider: "muse-agent-fallback",
    productionTarget: "worker",
    notes: "Chat-first Muse entry point. External agent endpoint and API key stay server-side; KV is reserved for non-secret Muse persona/config state.",
  },
  {
    method: "GET",
    path: "/api/session",
    audience: "auth",
    handler: "auth.session",
    responseContract: "SessionState",
    auth: "anonymous",
    stagedProvider: "session-cookie",
    productionTarget: "worker",
    notes: "Role-aware session state using the staged session cookie boundary.",
  },
  {
    method: "POST",
    path: "/api/auth/start",
    audience: "auth",
    handler: "auth.start",
    requestContract: "AuthStartRequest",
    responseContract: "AuthStartResponse",
    auth: "anonymous",
    stagedProvider: "session-cookie",
    productionTarget: "worker",
    notes: "Begins staged email challenge without external messaging provider.",
  },
  {
    method: "POST",
    path: "/api/auth/verify",
    audience: "auth",
    handler: "auth.verify",
    requestContract: "AuthVerifyRequest",
    responseContract: "AuthVerifyResponse",
    auth: "anonymous",
    stagedProvider: "session-cookie",
    productionTarget: "worker",
    notes: "Creates staged traveller or companion session.",
  },
  {
    method: "POST",
    path: "/api/session/role",
    audience: "auth",
    handler: "auth.roleSwitch",
    requestContract: "RoleSwitchRequest",
    responseContract: "AuthVerifyResponse",
    auth: "session",
    stagedProvider: "session-cookie",
    productionTarget: "worker",
    notes: "Switches staged customer role without exposing admin role.",
  },
  {
    method: "POST",
    path: "/api/auth/logout",
    audience: "auth",
    handler: "auth.logout",
    responseContract: "{ status: 'signed_out' }",
    auth: "session",
    stagedProvider: "session-cookie",
    productionTarget: "worker",
    notes: "Clears the staged session cookie.",
  },
  {
    method: "GET",
    path: "/api/traveller/dashboard",
    audience: "traveller",
    handler: "traveller.dashboard",
    responseContract: "TravellerDashboardResponse",
    auth: "role:traveller",
    stagedProvider: "stagedDataProvider.getTravellerDashboard",
    productionTarget: "D1",
    notes: "Protected traveller first surface with Muse chart, active plan, sessions, and saved profile demo state.",
  },
  {
    method: "GET",
    path: "/api/traveller/sessions",
    audience: "traveller",
    handler: "traveller.sessionList",
    responseContract: "TravellerSessionListResponse",
    auth: "role:traveller",
    stagedProvider: "stagedDataProvider.listTravellerSessions",
    productionTarget: "D1",
    notes: "Lists bookings/sessions as review-held plans, not instant booking confirmations.",
  },
  {
    method: "GET",
    path: "/api/traveller/sessions/:id",
    audience: "traveller",
    handler: "traveller.sessionDetail",
    responseContract: "TravellerSessionDetail",
    auth: "role:traveller",
    stagedProvider: "stagedDataProvider.getTravellerSession",
    productionTarget: "D1",
    notes: "Detailed protected session route with itinerary, Muse thread, safety, and payment compliance state.",
  },
  {
    method: "GET",
    path: "/api/traveller/discovery?city=&experience=&availability=&verified=",
    audience: "traveller",
    handler: "traveller.discovery",
    responseContract: "DiscoveryResponse",
    auth: "role:traveller",
    stagedProvider: "stagedDataProvider.listCompanionPreviews",
    productionTarget: "D1",
    notes: "Filters reviewed companion previews through API-shaped data rails.",
  },
  {
    method: "GET",
    path: "/api/traveller/companions/:id",
    audience: "traveller",
    handler: "traveller.profile",
    responseContract: "CompanionProfile",
    auth: "role:traveller",
    stagedProvider: "stagedDataProvider.getCompanionProfile",
    productionTarget: "D1",
    notes: "Returns visibility-safe profile fields only.",
  },
  {
    method: "GET",
    path: "/api/traveller/companions/:id/availability",
    audience: "traveller",
    handler: "traveller.availability",
    responseContract: "{ companionId, windows, note }",
    auth: "role:traveller",
    stagedProvider: "stagedDataProvider.getCompanionProfile",
    productionTarget: "D1",
    notes: "Returns availability planning context after profile visibility checks.",
  },
  {
    method: "POST",
    path: "/api/traveller/inquiries",
    audience: "traveller",
    handler: "traveller.createInquiry",
    requestContract: "TravellerInquiryRequest",
    responseContract: "TravellerInquiryCreateResponse",
    auth: "role:traveller",
    stagedProvider: "stagedDataProvider.createTravellerInquiry",
    productionTarget: "D1",
    notes: "Creates a private inquiry before introduction or payment.",
  },
  {
    method: "GET",
    path: "/api/traveller/inquiries",
    audience: "traveller",
    handler: "traveller.inquiryList",
    responseContract: "TravellerInquiryListResponse",
    auth: "role:traveller",
    stagedProvider: "stagedDataProvider.listTravellerInquiries",
    productionTarget: "D1",
    notes: "Lists private traveller inquiries.",
  },
  {
    method: "GET",
    path: "/api/traveller/inquiries/:id",
    audience: "traveller",
    handler: "traveller.inquiryDetail",
    responseContract: "TravellerInquiryDetail",
    auth: "role:traveller",
    stagedProvider: "stagedDataProvider.getTravellerInquiry",
    productionTarget: "D1",
    notes: "Returns inquiry detail and disabled payment state.",
  },
  {
    method: "DELETE",
    path: "/api/traveller/inquiries/:id",
    audience: "traveller",
    handler: "traveller.cancelInquiry",
    responseContract: "TravellerInquiryCreateResponse",
    auth: "role:traveller",
    stagedProvider: "bookingStore.transitionBookingStatus",
    productionTarget: "KV",
    notes: "Cancels an active inquiry (submitted, under_review, or routed). Past those stages it is too late.",
  },
  {
    method: "POST",
    path: "/api/traveller/inquiries/:id/stripe-checkout-session",
    audience: "payment",
    handler: "payment.stripeCheckoutSession",
    responseContract: "PaymentSessionResult",
    auth: "role:traveller",
    stagedProvider: "payment-provider",
    productionTarget: "payment-provider",
    notes: "Compliance-gated Stripe route; stripe_test can create hosted Checkout Sessions with server-side test keys.",
  },
  {
    method: "POST",
    path: "/api/traveller/inquiries/:id/payment-session",
    audience: "payment",
    handler: "payment.sessionCompatibility",
    responseContract: "PaymentSessionResult",
    auth: "role:traveller",
    stagedProvider: "payment-provider",
    productionTarget: "payment-provider",
    notes: "Provider-neutral payment-session route; defaults blocked unless local stripe_test is configured.",
  },
  {
    method: "GET",
    path: "/api/traveller/payments/:id",
    audience: "payment",
    handler: "payment.detail",
    responseContract: "PaymentRecordSummary",
    auth: "role:traveller",
    stagedProvider: "payment-provider",
    productionTarget: "D1",
    notes: "Payment detail remains disabled for compliance until provider approval.",
  },
  {
    method: "GET",
    path: "/api/payments/providers",
    audience: "payment",
    handler: "payment.providers",
    responseContract: "PaymentProviderSummary[]",
    auth: "anonymous",
    stagedProvider: "payment-provider",
    productionTarget: "KV",
    notes: "Lists payment adapter candidates and current availability status.",
  },
  {
    method: "GET",
    path: "/api/companion/inquiries/:id",
    audience: "companion",
    handler: "companion.inquiryDetail",
    responseContract: "CompanionSessionDetail",
    auth: "role:companion",
    stagedProvider: "stagedDataProvider.getCompanionSession",
    productionTarget: "D1",
    notes: "Companion-side inquiry view with private decision options.",
  },
  {
    method: "GET",
    path: "/api/companion/onboarding",
    audience: "companion",
    handler: "companion.onboarding",
    responseContract: "CompanionOnboardingState",
    auth: "role:companion",
    stagedProvider: "stagedDataProvider.getCompanionOnboarding",
    productionTarget: "D1",
    notes: "Returns draft profile, steps, options, progress, and guidance.",
  },
  {
    method: "GET",
    path: "/api/companion/dashboard",
    audience: "companion",
    handler: "companion.dashboard",
    responseContract: "CompanionDashboardResponse",
    auth: "role:companion",
    stagedProvider: "stagedDataProvider.getCompanionDashboard",
    productionTarget: "D1",
    notes: "Private companion home state.",
  },
  {
    method: "GET",
    path: "/api/companion/inquiries",
    audience: "companion",
    handler: "companion.inquiries",
    responseContract: "CompanionInquiryListResponse",
    auth: "role:companion",
    stagedProvider: "stagedDataProvider.listCompanionInquiries",
    productionTarget: "D1",
    notes: "Routed private inquiry list with no traveller contact leakage.",
  },
  {
    method: "POST",
    path: "/api/companion/inquiries/:id/accept",
    audience: "companion",
    handler: "companion.acceptInquiry",
    requestContract: "CompanionAcceptInquiryRequest",
    responseContract: "CompanionInquiryDecisionResponse",
    auth: "role:companion",
    stagedProvider: "bookingStore.transitionBookingStatus",
    productionTarget: "KV",
    notes: "Accepts a routed inquiry. Companion-only. Transitions routed → accepted. H2 limitation: any role:companion session can accept any routed inquiry until verified companion emails ship (post-H1).",
  },
  {
    method: "POST",
    path: "/api/companion/inquiries/:id/decline",
    audience: "companion",
    handler: "companion.declineInquiry",
    requestContract: "CompanionDeclineInquiryRequest",
    responseContract: "CompanionInquiryDecisionResponse",
    auth: "role:companion",
    stagedProvider: "bookingStore.transitionBookingStatus",
    productionTarget: "KV",
    notes: "Declines a routed inquiry with category + optional notes. Transitions routed → declined. H2 limitation: any role:companion session can decline any routed inquiry until verified companion emails ship (post-H1).",
  },
  {
    method: "POST",
    path: "/api/plans/:inquiryId/windows",
    audience: "traveller",
    handler: "plans.submitWindows",
    requestContract: "PlanWindowsRequest",
    responseContract: "PlanTravellerResponse",
    auth: "role:traveller",
    stagedProvider: "bookingStore.transitionBookingStatus",
    productionTarget: "KV",
    notes: "Traveller submits 2-3 candidate date windows. Transitions accepted → date_pending.",
  },
  {
    method: "POST",
    path: "/api/plans/:inquiryId/select-window",
    audience: "companion",
    handler: "plans.selectWindow",
    requestContract: "PlanWindowSelectionRequest",
    responseContract: "PlanCompanionResponse",
    auth: "role:companion",
    stagedProvider: "bookingStore.transitionBookingStatus",
    productionTarget: "KV",
    notes: "Companion picks one of the traveller's proposed windows. Transitions date_pending → date_proposed. Same H2 limitation: any role:companion session can act on any inquiry until verified companion emails ship.",
  },
  {
    method: "POST",
    path: "/api/plans/:inquiryId/confirm",
    audience: "traveller",
    handler: "plans.confirm",
    requestContract: "PlanConfirmRequest",
    responseContract: "PlanTravellerResponse",
    auth: "role:traveller",
    stagedProvider: "bookingStore.transitionBookingStatus",
    productionTarget: "KV",
    notes: "Traveller confirms the companion's selected window. Sets scheduledFor + durationMinutes + confirmedAt. Transitions date_proposed → date_confirmed.",
  },
  {
    method: "POST",
    path: "/api/plans/:inquiryId/hold",
    audience: "traveller",
    handler: "plans.hold",
    requestContract: "PaymentHoldRequest",
    responseContract: "PlanTravellerResponse",
    auth: "role:traveller",
    stagedProvider: "bookingStore.transitionBookingStatus",
    productionTarget: "KV",
    notes: "Places a payment hold on the confirmed plan. H4-stub: transitions date_confirmed → payment_held → session_scheduled (auto-advanced in non-prod) with no real Stripe call yet. Real Stripe checkout session creation lands in H4-real at end of roadmap.",
  },
  {
    method: "PATCH",
    path: "/api/companion/profile",
    audience: "companion",
    handler: "companion.updateProfile",
    requestContract: "CompanionProfileUpdateRequest",
    responseContract: "CompanionProfileUpdateResponse",
    auth: "role:companion",
    stagedProvider: "stagedDataProvider.updateCompanionProfile",
    productionTarget: "D1",
    notes: "Updates draft profile and returns refreshed onboarding state.",
  },
  {
    method: "PATCH",
    path: "/api/companion/visibility",
    audience: "companion",
    handler: "companion.updateVisibility",
    requestContract: "CompanionVisibilityUpdateRequest",
    responseContract: "CompanionProfileUpdateResponse",
    auth: "role:companion",
    stagedProvider: "stagedDataProvider.updateCompanionVisibility",
    productionTarget: "D1",
    notes: "Controls public exposure and inquiry readiness.",
  },
  {
    method: "PATCH",
    path: "/api/companion/availability",
    audience: "companion",
    handler: "companion.updateAvailability",
    requestContract: "CompanionAvailabilityUpdateRequest",
    responseContract: "CompanionProfileUpdateResponse",
    auth: "role:companion",
    stagedProvider: "stagedDataProvider.updateCompanionAvailability",
    productionTarget: "D1",
    notes: "Updates availability planning windows without creating booking urgency.",
  },
  {
    method: "POST",
    path: "/api/companion/submit-verification",
    audience: "companion",
    handler: "companion.submitVerification",
    requestContract: "CompanionVerificationSubmitRequest",
    responseContract: "CompanionVerificationSubmitResponse",
    auth: "role:companion",
    stagedProvider: "stagedDataProvider.submitCompanionVerification",
    productionTarget: "D1",
    notes: "Submits review and keeps public profile/inquiries paused.",
  },
  {
    method: "GET",
    path: "/api/safety/content",
    audience: "safety",
    handler: "safety.content",
    responseContract: "SafetyContent",
    auth: "anonymous",
    stagedProvider: "stagedDataProvider.getSafetyContent",
    productionTarget: "KV",
    notes: "Shared safety and discretion content.",
  },
  {
    method: "POST",
    path: "/api/safety/reports",
    audience: "safety",
    handler: "safety.report",
    requestContract: "SafetyReportRequest",
    responseContract: "SafetyReportResponse",
    auth: "session",
    stagedProvider: "stagedDataProvider.createSafetyReport",
    productionTarget: "D1",
    notes: "Creates staged safety report with safe non-leaking acknowledgement.",
  },
  {
    method: "GET",
    path: "/api/account",
    audience: "account",
    handler: "account.detail",
    responseContract: "AccountResponse",
    auth: "session",
    stagedProvider: "stagedDataProvider.getAccount",
    productionTarget: "D1",
    notes: "Role-aware account settings contract.",
  },
  {
    method: "PATCH",
    path: "/api/account/privacy",
    audience: "account",
    handler: "account.updatePrivacy",
    requestContract: "AccountPrivacyUpdateRequest",
    responseContract: "AccountPrivacyUpdateResponse",
    auth: "session",
    stagedProvider: "stagedDataProvider.updateAccountPrivacy",
    productionTarget: "D1",
    notes: "Updates account privacy settings without changing role or session.",
  },
  // ===== Pass E (2026-05-26) — data export, deletion, safety-report list =====
  {
    method: "POST",
    path: "/api/account/data-export",
    audience: "account",
    handler: "account.requestDataExport",
    responseContract: "AccountDataExportCreateResponse",
    auth: "session",
    stagedProvider: "stagedDataProvider.requestAccountDataExport",
    productionTarget: "KV",
    notes: "Queues a data export. Only one active request at a time; returns the existing record if already queued.",
  },
  {
    method: "GET",
    path: "/api/account/data-export",
    audience: "account",
    handler: "account.getDataExport",
    responseContract: "AccountDataExportRequest",
    auth: "session",
    stagedProvider: "stagedDataProvider.getAccountDataExport",
    productionTarget: "KV",
    notes: "Returns the latest data export request or null if none has been made.",
  },
  {
    method: "POST",
    path: "/api/account/deletion",
    audience: "account",
    handler: "account.requestDeletion",
    requestContract: "AccountDeletionCreateRequest",
    responseContract: "AccountDeletionResponse",
    auth: "session",
    stagedProvider: "stagedDataProvider.requestAccountDeletion",
    productionTarget: "KV",
    notes: "Soft-delete request with 7-day grace window. Requires confirmation string === 'DELETE'.",
  },
  {
    method: "DELETE",
    path: "/api/account/deletion",
    audience: "account",
    handler: "account.cancelDeletion",
    responseContract: "AccountDeletionResponse",
    auth: "session",
    stagedProvider: "stagedDataProvider.cancelAccountDeletion",
    productionTarget: "KV",
    notes: "Cancels a pending deletion request during the grace window.",
  },
  {
    method: "GET",
    path: "/api/account/safety-reports",
    audience: "account",
    handler: "account.listSafetyReports",
    responseContract: "AccountSafetyReportListResponse",
    auth: "session",
    stagedProvider: "stagedDataProvider.listAccountSafetyReports",
    productionTarget: "KV",
    notes: "Returns safety reports submitted by the current account (summary form, no internal review notes).",
  },
];

export function getRouteRegistry(): ApiRouteRegistryResponse {
  return {
    routes: apiRouteRegistry,
    requestIdHeader: "X-Request-Id",
    contractVersion: "2026-05-14.phase6",
  };
}
